# permissions for end users to view huaweicloudmachinetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-huawei
    app.kubernetes.io/managed-by: kustomize
  name: huaweicloudmachinetemplate-viewer-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - huaweicloudmachinetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - huaweicloudmachinetemplates/status
  verbs:
  - get
